Pip-info scripts added - Hazardouz
Shivansh-007/astounding-arapaimas-practice pull request #8
Opened 2021-07-09 11:16 UTC by kevinjacb

2021-07-09 11:22 UTC, Shivansh-007 commented
Lint before you push :D

2021-07-09 11:27 UTC, Shivansh-007 requested changes

2021-07-09 11:27 UTC, Shivansh-007 commented on hello_world/tabulate.py
> +# -*- coding: utf-8 -*-
This isn't required.

2021-07-09 11:27 UTC, Shivansh-007 commented on hello_world/tabulate.py
> +def make_table(raw_data: List[List[Any]],rows: List[List[Any]], labels: Optional[List[Any]] = None, centered: bool = False) -> str:
Remember next time, we are using python3.9 which includes `list`, `tuple` as a typehint. But no problem, I am fine with anything.

```suggestion
def make_table(raw_data: list[list[Any]],rows: list[list[Any]], labels: Optional[list[Any]] = None, centered: bool = False) -> str:
```

2021-07-09 11:31 UTC, JoeNibe requested changes
reviewed

2021-07-09 11:31 UTC, JoeNibe commented on hello_world/pip_info.py
> +# files = []
remove comment

2021-07-09 11:33 UTC, Shivansh-007 commented on hello_world/pip_info.py
> +# files = []
Any reason why? I don't see the need to do that.

2021-07-09 11:36 UTC, p0lygun commented on hello_world/tabulate.py
> +def make_table(raw_data: List[List[Any]],rows: List[List[Any]], labels: Optional[List[Any]] = None, centered: bool = False) -> str:
yh this should be changed

2021-07-09 11:39 UTC, JoeNibe commented on hello_world/tabulate.py
> +def make_table(raw_data: List[List[Any]],rows: List[List[Any]], labels: Optional[List[Any]] = None, centered: bool = False) -> str:
well i think its not required but makes it easier as you dont have to import more stuff.

2021-07-09 11:39 UTC, Shivansh-007 commented on hello_world/tabulate.py
> +def make_table(raw_data: List[List[Any]],rows: List[List[Any]], labels: Optional[List[Any]] = None, centered: bool = False) -> str:
Yup, 

> But no problem, I am fine with anything.

2021-07-09 11:39 UTC, JoeNibe commented on hello_world/pip_info.py
> +# files = []
just getting familiar with github. just wanted to check how suggestions work.

2021-07-09 11:42 UTC, p0lygun reviewed
just some linting issues that needs to be fixed

2021-07-09 11:57 UTC, JoeNibe approved these changes

2021-07-10 04:02 UTC, Shivansh-007 approved these changes

2021-07-10 04:02 UTC, merged